################################################################
### Products
################################################################

GET http://{{host}}/ HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/products HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/products/5d28f7f4b5a3e503a13cd1e1 HTTP/1.1
Content-Type: application/json

###

PATCH http://{{host}}/products/5d28f7f4b5a3e503a13cd1e1 HTTP/1.1
Content-Type: application/json

[
  {
    "propName": "name", "value": "Toyota Prius",
    "propName": "price", "value": "17890.00"
  }
]

###

DELETE http://{{host}}/products/5d2906e202e3392f7229bcf7 HTTP/1.1
Content-Type: application/json

###

POST http://{{host}}/products HTTP/1.1
# Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Node.js In Action
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

34.95
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="productImage"; filename="AJS.jpg"
Content-Type: image/jpg

< /home/ajspeller/AJS.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--


#######################################################
### Orders
#######################################################

GET http://{{host}}/orders HTTP/1.1
Content-Type: application/json

###

POST http://{{host}}/orders HTTP/1.1
Content-Type: application/json

{
  "productId":"5d2900aadb48282148e48073",
  "quantity":"199"
}

###

GET http://{{host}}/orders HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/orders/5d292de0abd6647ed12a5434 HTTP/1.1
Content-Type: application/json

###

DELETE http://{{host}}/orders/5d292de7abd6647ed12a5435 HTTP/1.1
Content-Type: application/json

#######################################################
### User
#######################################################

POST http://{{host}}/user/signup HTTP/1.1
Content-Type: application/json

{
  "email": "ajspeller@gmail.com",
  "password": "password123"
}

###

POST http://{{host}}/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "ajspeller@gmail.com",
  "password": "password123"
}

###

DELETE http://{{host}}/user/5d2b641741abd209f194c619 HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/user HTTP/1.1
Content-Type: application/json

###

POST http://{{host}}/signin HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="email"

Node.js In Action
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="password"

34.95
------WebKitFormBoundary7MA4YWxkTrZu0gW--