###

GET http://localhost:3000/ HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/products HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/products/5d28f7f4b5a3e503a13cd1e1 HTTP/1.1
Content-Type: application/json

###

PATCH http://localhost:3000/products/5d28f7f4b5a3e503a13cd1e1 HTTP/1.1
Content-Type: application/json

[
  {
    "propName": "name", "value": "Toyota Prius",
    "propName": "price", "value": "17890.00"
  }
]

###

DELETE http://localhost:3000/products/5d2906e202e3392f7229bcf7 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/products HTTP/1.1
Content-Type: application/json

{
  "name": "Manning Book",
  "price": "39.99"
}

#######################################################
#######################################################

GET http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/orders HTTP/1.1
Content-Type: application/json

{
  "productId":"99",
  "quantity":"42"
}

###

GET http://localhost:3000/orders/kjkj HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:3000/orders/jhjhh HTTP/1.1
Content-Type: application/json
